FROM python:3.8
EXPOSE 80
ENV PYTHONUNBUFFERED=1
ENV PYTHONDONTWRITEBYTECODE=1
WORKDIR /new_dir
COPY requirements.txt .
RUN ["pip", "install", "-r", "requirements.txt"]

COPY . /new_dir/
ENTRYPOINT ["python", "manage.py", "migrate"]